name: Daily Antam Puppeteer Scrape

on:
  schedule:
    - cron: "0 2 * * *"   # 09:00 WIB
  workflow_dispatch:

permissions:
  contents: write   # penting biar bisa git push

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm run scrape

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Update gold data $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push

      - name: Kirim Telegram Notif
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.8342432038:AAEk6bQmIzUQJpR2DxCC--t-z1g3dHPkUpo }}/sendMessage \
          -d chat_id=${{ secrets.7643732899 }} \
          -d text="✅ Gold Scraper sukses update $(date +'%Y-%m-%d %H:%M:%S WIB')%0A🔗 https://raw.githubusercontent.com/dedychristian-deploy/gold-antam-scraper/main/data/gold-latest.json"

